# Site settings
author: Mark Stabler
title: Flatiron School Blogs
header-img: img/home-bg.png
email: mark@markstabler.com
copyright_name: Mark Stabler
description: > # this means to ignore newlines until "baseurl:"
  School Projects and Other Coding Mishaps
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  marcon29

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
